= Comparison of different Parsers/Compiler Frameworks
:source-highlighter: highlightjs

== About
Each framework is written to convert the following code sample from Scala to C:
[source, scala]
object Main extends App {
  val y = (5 + 3) * 5;
  val x = 10;
  println(x + y);
  return x + y * 2;
}

The sample programs also support a subset of Scala (only ints, no functions or variables ('val's are immutable) & newlines don't act as semicolons), but are more designed to give a basic example of lexing, parsing and code generation from each.

== Scala (Scala Parser Combinators)
=== About
TODO: Write Description

=== Running the Example
Using the mill script (todo: include mill script), run `./mill _.run` (`./mill.bat _.run` on windows?) in the link:Scala[Scala] directory.

== Erlang (Leex & Yecc)
=== About
TODO: Write Description

=== Running the Example
With Erlang installed (available from all package managers I've seen & on most architectures), run `escript compiler.erl` in the link:Erlang[Erlang] directory.

== Haskell (Parsec)
=== About
TODO: Write Description

=== Running the Example
With Haskell (GHC & cabal) installed & running `cabal install --lib parsec`, run `ghc main`, followed by `./main` in the link:Haskell[Haskell] directory.

== C/C++ (Flex & Yacc)
TODO: Write Example

== Java (ANTLR)
TODO: Write Example

== Python (Lark or PLY)?
TODO: Write Example

== C# (Sprache)
TODO: Write Example

== JavaScript (PEGjs)
TODO: Write Example

== Others
There are a huge number of other libraries you could use, the above are just a small sample from some popular languages. Feel free to find or even write your own library in your favourite language.
